controllers:
  src: "app/Controllers"
  posfix: "Controller"
models:
  path: "app/Models"
views:
  path: "app/Views"
  cache: "storage/cache/views"

envirotment:
  path: "app/Views"

services:
  auth: true

translation:
  file_loader: "config/lang"